proper handling of exit codes

diff --git a/minecraftd.sh.in b/minecraftd.sh.in
--- a/minecraftd.sh.in
+++ b/minecraftd.sh.in
@@ -149,8 +149,10 @@ idle_server_daemon() {
 					while true; do
 						echo -n "Netcat: "
 						if [[ "${IDLE_WAKE_MODE}" == "whitelist" ]]; then
+							set +e # temporarily disable set -e to get the exit status
 							"${NETCAT_CMD[@]}" -v -l -p "${GAME_PORT}" 2>&1 | (grep -m1 -a -F -f <(${IDLE_WAKE_WHITELIST_CMD[@]} "${IDLE_WAKE_WHITELIST}") && pkill -P $$ "${NETCAT_CMD[@]}")
 							exit_status=$?
+							set -e
 							echo -n "Netcat caught a connection. "
 							if [[ $exit_status -ne 0 ]]; then # this could also happen if pkill somehow fails
 								echo "But it didn't match anything in the whitelist..."
@@ -158,7 +160,7 @@ idle_server_daemon() {
 								break
 							fi
 						else
-							"${NETCAT_CMD[@]}" -v -l -p "${GAME_PORT}" 2>&1 | (grep -m1 -i "connect" && pkill -P $$ "${NETCAT_CMD[@]}")
+							"${NETCAT_CMD[@]}" -v -l -p "${GAME_PORT}" 2>&1 | (grep -m1 -i "connect" && pkill -P $$ "${NETCAT_CMD[@]}") || true
 							echo -n "Netcat caught a connection. "
 							break
 						fi
