refinements

diff --git a/minecraftd.sh.in b/minecraftd.sh.in
--- a/minecraftd.sh.in
+++ b/minecraftd.sh.in
@@ -49,6 +49,8 @@ source /etc/conf.d/"@GAME@" 2>/dev/null || >&2 echo "Could not source /etc/conf.
 set -u
 # Exit if a single command breaks and its failure is not handled accordingly
 set -e
+#debug:
+#trap 'echo "Error on line $LINENO: $BASH_COMMAND"' ERR
 
 # Check whether sudo is needed at all
 if [[ "$(whoami)" == "${GAME_USER}" ]]; then
@@ -120,7 +122,8 @@ idle_server_daemon() {
 
 	if [[ "${IDLE_WAKE_MODE}" == "webwake" ]]; then
 		TMP_DIR=$(mktemp -d /tmp/@INAME@-ipc.XXXXXX)
-		trap rm -rf "$TMP_DIR" EXIT
+		echo "$TMP_DIR"
+		trap 'rm -rf $TMP_DIR"' EXIT
 
 		CMD_FIFO="$TMP_DIR/cmd.fifo"
 		STATUS_FIFO="$TMP_DIR/status.fifo"
@@ -138,14 +141,14 @@ idle_server_daemon() {
 			for i in {1..100}; do
 				sleep 0.1
 				if ! socket_has_session "${WEBWAKE_SESSION_NAME}"; then
-					"${SUDO_CMD[@]}" tmux -L "${SESSION_NAME}" new-session -s "${WEBWAKE_SESSION_NAME}" -d "${INAME}-web-wake"
+					"${SUDO_CMD[@]}" tmux -L "${SESSION_NAME}" new-session -s "${WEBWAKE_SESSION_NAME}" -d "${INAME}-web-wake $CMD_FIFO $STATUS_FIFO"
 					break
 				fi
 				[[ $i -eq 100 ]] && echo -e "An \e[39;1merror\e[0m occurred while trying to reset the web-wake server!"
 			done
 		else
-			echo -en "Starting idle server daemon..."
-			"${SUDO_CMD[@]}" tmux -L "${SESSION_NAME}" new-session -s "${WEBWAKE_SESSION_NAME}" -d "${INAME}-web-wake"
+			echo -en "Starting web-wake server daemon..."
+			"${SUDO_CMD[@]}" tmux -L "${SESSION_NAME}" new-session -s "${WEBWAKE_SESSION_NAME}" -d "${INAME}-web-wake $CMD_FIFO $STATUS_FIFO"
 			echo -e "\e[39;1m done\e[0m"
 		fi
 
@@ -296,7 +299,7 @@ server_start() {
 			done
 		else
 			echo -en "Starting idle server daemon..."
-			"${SUDO_CMD[@]}" tmux -L "${SESSION_NAME}" new-session -s "${IDLE_SESSION_NAME}" -d "${INAME} idle_server_daemon"
+			"${SUDO_CMD[@]}" tmux -L "${SESSION_NAME}" new-session -s "${IDLE_SESSION_NAME}" -d "bash -x /usr/bin/minecraftd idle_server_daemon"
 			echo -e "\e[39;1m done\e[0m"
 		fi
 	fi
