cpp-bash basic integration

diff --git a/minecraftd.sh.in b/minecraftd.sh.in
--- a/minecraftd.sh.in
+++ b/minecraftd.sh.in
@@ -30,6 +30,7 @@ declare -r GAME="@GAME@"
 [[ -n "${IDLE_IF_TIME}" ]]      && declare -r IDLE_IF_TIME=${IDLE_IF_TIME} || IDLE_IF_TIME="@IDLE_IF_TIME@"
 [[ -n "${IDLE_WAKE_MODE}" ]]    && declare -r IDLE_WAKE_MODE=${IDLE_WAKE_MODE} 	|| IDLE_WAKE_MODE="@IDLE_WAKE_MODE@"
 [[ -n "${IDLE_WAKE_WHITELIST}" ]]    && declare -r IDLE_WAKE_WHITELIST=${IDLE_WAKE_WHITELIST} 	|| IDLE_WAKE_WHITELIST="@IDLE_WAKE_WHITELIST@"
+[[ -n "${WEBWAKE_SESSION_NAME}" ]] && declare -r WEBWAKE_SESSION_NAME=${WEBWAKE_SESSION_NAME} || WEBWAKE_SESSION_NAME="@WEBWAKE_SESSION_NAME@"
 
 # Additional configuration options which only few may need to alter
 [[ -n "${GAME_COMMAND_DUMP}" ]] && declare -r GAME_COMMAND_DUMP=${GAME_COMMAND_DUMP} || GAME_COMMAND_DUMP="@GAME_COMMAND_DUMP@"
@@ -115,6 +116,41 @@ idle_server_daemon() {
 		>&2 echo "Somehow this hidden function was not executed by the ${GAME_USER} user."
 		>&2 echo "This should not have happend. Are you messing around with this script? :P"
 		exit 22
+	fi
+
+	if [[ "${IDLE_WAKE_MODE}" == "web-wake" ]]; then
+		TMP_DIR=$(mktemp -d /tmp/@INAME@-ipc.XXXXXX)
+		trap rm -rf "$TMP_DIR" EXIT
+
+		CMD_FIFO="$TMP_DIR/cmd.fifo"
+		STATUS_FIFO="$TMP_DIR/status.fifo"
+		mkfifo "$CMD_FIFO" "$STATUS_FIFO"
+
+		if !(command -v "${INAME}-web-wake" &> /dev/null); then
+			>&2 echo "Web-wake executable was not found!"
+			exit 127
+		fi
+
+		#TODO refine how webwake is started
+		if socket_has_session "${WEBWAKE_SESSION_NAME}"; then
+			"${SUDO_CMD[@]}" tmux -L "${SESSION_NAME}" kill-session -t "${WEBWAKE_SESSION_NAME}"
+			# Restart as soon as the idle_server_daemon has shut down completely
+			for i in {1..100}; do
+				sleep 0.1
+				if ! socket_has_session "${WEBWAKE_SESSION_NAME}"; then
+					"${SUDO_CMD[@]}" tmux -L "${SESSION_NAME}" new-session -s "${WEBWAKE_SESSION_NAME}" -d "${INAME}-web-wake"
+					break
+				fi
+				[[ $i -eq 100 ]] && echo -e "An \e[39;1merror\e[0m occurred while trying to reset the web-wake server!"
+			done
+		else
+			echo -en "Starting idle server daemon..."
+			"${SUDO_CMD[@]}" tmux -L "${SESSION_NAME}" new-session -s "${WEBWAKE_SESSION_NAME}" -d "${INAME}-web-wake"
+			echo -e "\e[39;1m done\e[0m"
+		fi
+
+		exec 3< "$CMD_FIFO"
+		exec 4> "$STATUS_FIFO"
 	fi
 
 	# Time in seconds for which no player was on the server
