reworked the listening loop

diff --git a/minecraftd.sh.in b/minecraftd.sh.in
--- a/minecraftd.sh.in
+++ b/minecraftd.sh.in
@@ -146,13 +146,24 @@ idle_server_daemon() {
 					# Reset timer and give the player 300 seconds to connect after pinging
 					no_player=$(( IDLE_IF_TIME - 300 ))
 					# Game server is down, listen on port ${GAME_PORT} for incoming connections
-					echo -n "Netcat: "
-					if [[ "${IDLE_WAKE_MODE}" == "whitelist" ]]; then
-						"${NETCAT_CMD[@]}" -v -l -p "${GAME_PORT}" 2>&1 | (grep -m1 -a -F -f <(${IDLE_WAKE_WHITELIST_CMD[@]} ${IDLE_WAKE_WHITELIST}) && pkill -P $$ "${NETCAT_CMD[@]}") || true
-					else
-						"${NETCAT_CMD[@]}" -v -l -p "${GAME_PORT}" 2>&1 | (grep -m1 -i "connect" && pkill -P $$ "${NETCAT_CMD[@]}") || true
-					fi
-					echo "Netcat caught a connection. The server is coming up again..."
+					while true; do
+						echo -n "Netcat: "
+						if [[ "${IDLE_WAKE_MODE}" == "whitelist" ]]; then
+							"${NETCAT_CMD[@]}" -v -l -p "${GAME_PORT}" 2>&1 | (grep -m1 -a -F -f <(${IDLE_WAKE_WHITELIST_CMD[@]} "${IDLE_WAKE_WHITELIST}") && pkill -P $$ "${NETCAT_CMD[@]}")
+							exit_status=$?
+							echo -n "Netcat caught a connection. "
+							if [[ $exit_status -ne 0 ]]; then # this could also happen if pkill somehow fails
+								echo "But it didn't match anything in the whitelist..."
+							else
+								break
+							fi
+						else
+							"${NETCAT_CMD[@]}" -v -l -p "${GAME_PORT}" 2>&1 | (grep -m1 -i "connect" && pkill -P $$ "${NETCAT_CMD[@]}")
+							echo -n "Netcat caught a connection. "
+							break
+						fi
+					done
+					echo "The server is coming up again..."
 					IDLE_SERVER="false" ${INAME} start
 				fi
 			else
